export const ROLES = {
  platform_owner: 'platform_owner',
  platform_admin: 'platform_admin',
  organisation_owner: 'organisation_owner',
  practice_manager: 'practice_manager',
  dentist: 'dentist',
  specialist: 'specialist',
  hygienist: 'hygienist',
  dental_therapist: 'dental_therapist',
  dental_assistant: 'dental_assistant',
  receptionist: 'receptionist',
  billing_officer: 'billing_officer',
  finance: 'finance',
  read_only: 'read_only',
} as const;

export type RoleKey = keyof typeof ROLES;
export type RoleValue = (typeof ROLES)[RoleKey];

export const PERMISSIONS = {
  patient: ['read', 'create', 'update', 'delete'],
  clinical: ['read', 'create', 'sign', 'amend'],
  dental_chart: ['read', 'update'],
  treatment_plan: ['read', 'create', 'approve'],
  billing: ['read', 'create'],
  payment: ['process'],
  claims: ['submit', 'read'],
  claims_integration: ['read', 'manage'],
  imaging: ['read', 'upload', 'create', 'update', 'delete'],
  reports: ['read'],
  settings: ['manage'],
  users: ['manage'],
  audit: ['read'],
  calendar: ['read', 'create', 'update', 'delete'],
  service: ['read', 'create', 'update', 'delete'],
  fee: ['read', 'create', 'update', 'delete'],
  invoice: ['read', 'create', 'update', 'delete'],
  refund: ['read', 'create', 'update'],
  statement: ['read'],
  receipt: ['read'],
  communication: ['read', 'manage'],
  notification: ['read', 'create'],
  message: ['read', 'send'],
  recall: ['read', 'manage'],
} as const;

export type Permission = {
  resource: string;
  action: string;
};

export const DEFAULT_PERMISSIONS: Record<RoleValue, Permission[]> = {
  platform_owner: Object.keys(PERMISSIONS).flatMap((resource) =>
    PERMISSIONS[resource as keyof typeof PERMISSIONS].map((action) => ({ resource, action })),
  ),
  platform_admin: Object.keys(PERMISSIONS).flatMap((resource) =>
    PERMISSIONS[resource as keyof typeof PERMISSIONS].map((action) => ({ resource, action })),
  ),
  organisation_owner: Object.keys(PERMISSIONS).flatMap((resource) =>
    PERMISSIONS[resource as keyof typeof PERMISSIONS].map((action) => ({ resource, action })),
  ),
  practice_manager: [
    { resource: 'patient', action: 'read' },
    { resource: 'clinical', action: 'read' },
    { resource: 'billing', action: 'read' },
    { resource: 'reports', action: 'read' },
    { resource: 'settings', action: 'manage' },
    { resource: 'users', action: 'manage' },
    { resource: 'treatment_plan', action: 'read' },
    { resource: 'service', action: 'read' },
    { resource: 'fee', action: 'read' },
    { resource: 'invoice', action: 'read' },
    { resource: 'payment', action: 'process' },
    { resource: 'refund', action: 'read' },
    { resource: 'statement', action: 'read' },
    { resource: 'receipt', action: 'read' },
    { resource: 'claims', action: 'read' },
    { resource: 'claims', action: 'submit' },
    { resource: 'claims_integration', action: 'read' },
    { resource: 'claims_integration', action: 'manage' },
    { resource: 'communication', action: 'read' },
    { resource: 'communication', action: 'manage' },
    { resource: 'notification', action: 'read' },
    { resource: 'message', action: 'read' },
    { resource: 'message', action: 'send' },
    { resource: 'recall', action: 'read' },
    { resource: 'recall', action: 'manage' },
  ],
  dentist: [
    { resource: 'patient', action: 'read' },
    { resource: 'clinical', action: 'read' },
    { resource: 'clinical', action: 'create' },
    { resource: 'clinical', action: 'sign' },
    { resource: 'dental_chart', action: 'read' },
    { resource: 'dental_chart', action: 'update' },
    { resource: 'treatment_plan', action: 'read' },
    { resource: 'treatment_plan', action: 'create' },
    { resource: 'treatment_plan', action: 'approve' },
    { resource: 'imaging', action: 'read' },
    { resource: 'imaging', action: 'upload' },
    { resource: 'service', action: 'read' },
    { resource: 'fee', action: 'read' },
    { resource: 'invoice', action: 'read' },
    { resource: 'statement', action: 'read' },
    { resource: 'receipt', action: 'read' },
    { resource: 'reports', action: 'read' },
    { resource: 'communication', action: 'read' },
    { resource: 'notification', action: 'read' },
    { resource: 'message', action: 'read' },
    { resource: 'message', action: 'send' },
    { resource: 'recall', action: 'read' },
    { resource: 'recall', action: 'manage' },
  ],
  specialist: [
    { resource: 'patient', action: 'read' },
    { resource: 'clinical', action: 'read' },
    { resource: 'clinical', action: 'create' },
    { resource: 'clinical', action: 'sign' },
    { resource: 'imaging', action: 'read' },
    { resource: 'service', action: 'read' },
    { resource: 'fee', action: 'read' },
    { resource: 'invoice', action: 'read' },
    { resource: 'statement', action: 'read' },
    { resource: 'receipt', action: 'read' },
    { resource: 'reports', action: 'read' },
    { resource: 'communication', action: 'read' },
    { resource: 'notification', action: 'read' },
    { resource: 'message', action: 'read' },
    { resource: 'message', action: 'send' },
    { resource: 'recall', action: 'read' },
    { resource: 'recall', action: 'manage' },
  ],
  hygienist: [
    { resource: 'patient', action: 'read' },
    { resource: 'clinical', action: 'read' },
    { resource: 'clinical', action: 'create' },
    { resource: 'dental_chart', action: 'read' },
    { resource: 'treatment_plan', action: 'read' },
    { resource: 'treatment_plan', action: 'create' },
    { resource: 'service', action: 'read' },
    { resource: 'fee', action: 'read' },
    { resource: 'invoice', action: 'read' },
    { resource: 'statement', action: 'read' },
    { resource: 'receipt', action: 'read' },
    { resource: 'reports', action: 'read' },
    { resource: 'communication', action: 'read' },
    { resource: 'notification', action: 'read' },
    { resource: 'message', action: 'read' },
    { resource: 'message', action: 'send' },
    { resource: 'recall', action: 'read' },
    { resource: 'recall', action: 'manage' },
  ],
  dental_therapist: [
    { resource: 'patient', action: 'read' },
    { resource: 'clinical', action: 'read' },
    { resource: 'clinical', action: 'create' },
    { resource: 'dental_chart', action: 'read' },
    { resource: 'service', action: 'read' },
    { resource: 'fee', action: 'read' },
    { resource: 'invoice', action: 'read' },
    { resource: 'statement', action: 'read' },
    { resource: 'receipt', action: 'read' },
    { resource: 'reports', action: 'read' },
    { resource: 'communication', action: 'read' },
    { resource: 'notification', action: 'read' },
    { resource: 'message', action: 'read' },
    { resource: 'message', action: 'send' },
    { resource: 'recall', action: 'read' },
    { resource: 'recall', action: 'manage' },
  ],
  dental_assistant: [
    { resource: 'patient', action: 'read' },
    { resource: 'clinical', action: 'read' },
    { resource: 'imaging', action: 'read' },
    { resource: 'service', action: 'read' },
    { resource: 'fee', action: 'read' },
    { resource: 'invoice', action: 'read' },
    { resource: 'statement', action: 'read' },
    { resource: 'receipt', action: 'read' },
    { resource: 'reports', action: 'read' },
    { resource: 'communication', action: 'read' },
    { resource: 'notification', action: 'read' },
    { resource: 'message', action: 'read' },
    { resource: 'message', action: 'send' },
    { resource: 'recall', action: 'read' },
    { resource: 'recall', action: 'manage' },
  ],
  receptionist: [
    { resource: 'patient', action: 'read' },
    { resource: 'patient', action: 'create' },
    { resource: 'billing', action: 'read' },
    { resource: 'service', action: 'read' },
    { resource: 'fee', action: 'read' },
    { resource: 'invoice', action: 'read' },
    { resource: 'invoice', action: 'create' },
    { resource: 'payment', action: 'process' },
    { resource: 'statement', action: 'read' },
    { resource: 'receipt', action: 'read' },
    { resource: 'reports', action: 'read' },
    { resource: 'communication', action: 'read' },
    { resource: 'communication', action: 'manage' },
    { resource: 'notification', action: 'read' },
    { resource: 'message', action: 'read' },
    { resource: 'message', action: 'send' },
    { resource: 'recall', action: 'read' },
    { resource: 'recall', action: 'manage' },
  ],
  billing_officer: [
    { resource: 'patient', action: 'read' },
    { resource: 'billing', action: 'read' },
    { resource: 'billing', action: 'create' },
    { resource: 'payment', action: 'process' },
    { resource: 'claims', action: 'read' },
    { resource: 'claims', action: 'submit' },
    { resource: 'claims_integration', action: 'read' },
    { resource: 'claims_integration', action: 'manage' },
    { resource: 'service', action: 'read' },
    { resource: 'fee', action: 'read' },
    { resource: 'fee', action: 'create' },
    { resource: 'invoice', action: 'read' },
    { resource: 'invoice', action: 'create' },
    { resource: 'refund', action: 'read' },
    { resource: 'refund', action: 'create' },
    { resource: 'statement', action: 'read' },
    { resource: 'receipt', action: 'read' },
    { resource: 'communication', action: 'read' },
    { resource: 'communication', action: 'manage' },
    { resource: 'notification', action: 'read' },
    { resource: 'message', action: 'read' },
    { resource: 'message', action: 'send' },
    { resource: 'recall', action: 'read' },
    { resource: 'recall', action: 'manage' },
  ],
  finance: [
    { resource: 'patient', action: 'read' },
    { resource: 'billing', action: 'read' },
    { resource: 'payment', action: 'process' },
    { resource: 'claims', action: 'read' },
    { resource: 'claims', action: 'submit' },
    { resource: 'claims_integration', action: 'read' },
    { resource: 'claims_integration', action: 'manage' },
    { resource: 'reports', action: 'read' },
    { resource: 'service', action: 'read' },
    { resource: 'fee', action: 'read' },
    { resource: 'invoice', action: 'read' },
    { resource: 'refund', action: 'read' },
    { resource: 'statement', action: 'read' },
    { resource: 'receipt', action: 'read' },
    { resource: 'communication', action: 'read' },
    { resource: 'notification', action: 'read' },
    { resource: 'message', action: 'read' },
    { resource: 'message', action: 'send' },
    { resource: 'recall', action: 'read' },
    { resource: 'recall', action: 'manage' },
  ],
  read_only: [
    { resource: 'patient', action: 'read' },
    { resource: 'clinical', action: 'read' },
    { resource: 'billing', action: 'read' },
    { resource: 'reports', action: 'read' },
    { resource: 'service', action: 'read' },
    { resource: 'fee', action: 'read' },
    { resource: 'invoice', action: 'read' },
    { resource: 'statement', action: 'read' },
    { resource: 'receipt', action: 'read' },
    { resource: 'communication', action: 'read' },
    { resource: 'notification', action: 'read' },
    { resource: 'message', action: 'read' },
    { resource: 'recall', action: 'read' },
  ],
};
