/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiKeysIndexRouteImport } from './routes/api-keys/index'
import { Route as AppointmentRemindersIndexRouteImport } from './routes/appointment-reminders/index'
import { Route as AppointmentTypesIndexRouteImport } from './routes/appointment-types/index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as ChairsIndexRouteImport } from './routes/chairs/index'
import { Route as ClaimIntegrationsIndexRouteImport } from './routes/claim-integrations/index'
import { Route as ClinicalNotesIndexRouteImport } from './routes/clinical-notes/index'
import { Route as CommunicationPreferencesIndexRouteImport } from './routes/communication-preferences/index'
import { Route as CommunicationTemplatesIndexRouteImport } from './routes/communication-templates/index'
import { Route as DashboardExampleIndexRouteImport } from './routes/dashboard-example/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DentalChartsIndexRouteImport } from './routes/dental-charts/index'
import { Route as FeesIndexRouteImport } from './routes/fees/index'
import { Route as ForbiddenIndexRouteImport } from './routes/forbidden/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as ImagingImagesIndexRouteImport } from './routes/imaging-images/index'
import { Route as ImagingIntegrationsIndexRouteImport } from './routes/imaging-integrations/index'
import { Route as ImagingStudiesIndexRouteImport } from './routes/imaging-studies/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as MfaVerifyIndexRouteImport } from './routes/mfa-verify/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as PatientPortalIndexRouteImport } from './routes/patient-portal/index'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsIdRouteImport } from './routes/patients/$id'
import { Route as PaymentsIndexRouteImport } from './routes/payments/index'
import { Route as PeriodontalRecordsIndexRouteImport } from './routes/periodontal-records/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers/index'
import { Route as RecallsIndexRouteImport } from './routes/recalls/index'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts/index'
import { Route as RefundsIndexRouteImport } from './routes/refunds/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsSectionRouteImport } from './routes/settings/$section'
import { Route as StatementsIndexRouteImport } from './routes/statements/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as ToothConditionsIndexRouteImport } from './routes/tooth-conditions/index'
import { Route as TreatmentHistoryIndexRouteImport } from './routes/treatment-history/index'
import { Route as TreatmentPlansIndexRouteImport } from './routes/treatment-plans/index'
import { Route as UnauthorizedIndexRouteImport } from './routes/unauthorized/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TenantIdDashboardIndexRouteImport } from './routes/$tenantId/dashboard/index'
import { Route as TenantIdDashboardSplatRouteImport } from './routes/$tenantId/dashboard/$'
import { Route as PatientPortalAppointmentsIndexRouteImport } from './routes/patient-portal/appointments/index'
import { Route as PatientPortalBillingIndexRouteImport } from './routes/patient-portal/billing/index'
import { Route as PatientPortalDashboardIndexRouteImport } from './routes/patient-portal/dashboard/index'
import { Route as PatientPortalDocumentsIndexRouteImport } from './routes/patient-portal/documents/index'
import { Route as PatientPortalFormsIndexRouteImport } from './routes/patient-portal/forms/index'
import { Route as PatientPortalLoginIndexRouteImport } from './routes/patient-portal/login/index'
import { Route as PatientPortalMessagesIndexRouteImport } from './routes/patient-portal/messages/index'
import { Route as PatientPortalNotificationsIndexRouteImport } from './routes/patient-portal/notifications/index'
import { Route as PatientPortalPaymentsIndexRouteImport } from './routes/patient-portal/payments/index'
import { Route as PatientPortalTreatmentPlansIndexRouteImport } from './routes/patient-portal/treatment-plans/index'
import { Route as ReportsAppointmentsIndexRouteImport } from './routes/reports/appointments/index'
import { Route as ReportsCollectionsIndexRouteImport } from './routes/reports/collections/index'
import { Route as ReportsDashboardIndexRouteImport } from './routes/reports/dashboard/index'
import { Route as ReportsPatientsIndexRouteImport } from './routes/reports/patients/index'
import { Route as ReportsPractitionersIndexRouteImport } from './routes/reports/practitioners/index'
import { Route as ReportsProductionIndexRouteImport } from './routes/reports/production/index'
import { Route as ReportsRecallsIndexRouteImport } from './routes/reports/recalls/index'
import { Route as ReportsRevenueIndexRouteImport } from './routes/reports/revenue/index'
import { Route as SettingsLocationsIndexRouteImport } from './routes/settings/locations/index'
import { Route as SettingsOrganisationIndexRouteImport } from './routes/settings/organisation/index'
import { Route as SettingsPracticeIndexRouteImport } from './routes/settings/practice/index'
import { Route as SettingsSecurityIndexRouteImport } from './routes/settings/security/index'

const ApiKeysIndexRoute = ApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRemindersIndexRoute =
  AppointmentRemindersIndexRouteImport.update({
    id: '/appointment-reminders/',
    path: '/appointment-reminders/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppointmentTypesIndexRoute = AppointmentTypesIndexRouteImport.update({
  id: '/appointment-types/',
  path: '/appointment-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChairsIndexRoute = ChairsIndexRouteImport.update({
  id: '/chairs/',
  path: '/chairs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimIntegrationsIndexRoute = ClaimIntegrationsIndexRouteImport.update({
  id: '/claim-integrations/',
  path: '/claim-integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalNotesIndexRoute = ClinicalNotesIndexRouteImport.update({
  id: '/clinical-notes/',
  path: '/clinical-notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationPreferencesIndexRoute =
  CommunicationPreferencesIndexRouteImport.update({
    id: '/communication-preferences/',
    path: '/communication-preferences/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommunicationTemplatesIndexRoute =
  CommunicationTemplatesIndexRouteImport.update({
    id: '/communication-templates/',
    path: '/communication-templates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardExampleIndexRoute = DashboardExampleIndexRouteImport.update({
  id: '/dashboard-example/',
  path: '/dashboard-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalChartsIndexRoute = DentalChartsIndexRouteImport.update({
  id: '/dental-charts/',
  path: '/dental-charts/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesIndexRoute = FeesIndexRouteImport.update({
  id: '/fees/',
  path: '/fees/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenIndexRoute = ForbiddenIndexRouteImport.update({
  id: '/forbidden/',
  path: '/forbidden/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagingImagesIndexRoute = ImagingImagesIndexRouteImport.update({
  id: '/imaging-images/',
  path: '/imaging-images/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagingIntegrationsIndexRoute =
  ImagingIntegrationsIndexRouteImport.update({
    id: '/imaging-integrations/',
    path: '/imaging-integrations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImagingStudiesIndexRoute = ImagingStudiesIndexRouteImport.update({
  id: '/imaging-studies/',
  path: '/imaging-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaVerifyIndexRoute = MfaVerifyIndexRouteImport.update({
  id: '/mfa-verify/',
  path: '/mfa-verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalIndexRoute = PatientPortalIndexRouteImport.update({
  id: '/patient-portal/',
  path: '/patient-portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodontalRecordsIndexRoute = PeriodontalRecordsIndexRouteImport.update({
  id: '/periodontal-records/',
  path: '/periodontal-records/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecallsIndexRoute = RecallsIndexRouteImport.update({
  id: '/recalls/',
  path: '/recalls/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsIndexRoute = RefundsIndexRouteImport.update({
  id: '/refunds/',
  path: '/refunds/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsIndexRoute = StatementsIndexRouteImport.update({
  id: '/statements/',
  path: '/statements/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToothConditionsIndexRoute = ToothConditionsIndexRouteImport.update({
  id: '/tooth-conditions/',
  path: '/tooth-conditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentHistoryIndexRoute = TreatmentHistoryIndexRouteImport.update({
  id: '/treatment-history/',
  path: '/treatment-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentPlansIndexRoute = TreatmentPlansIndexRouteImport.update({
  id: '/treatment-plans/',
  path: '/treatment-plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedIndexRoute = UnauthorizedIndexRouteImport.update({
  id: '/unauthorized/',
  path: '/unauthorized/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIdDashboardIndexRoute = TenantIdDashboardIndexRouteImport.update({
  id: '/$tenantId/dashboard/',
  path: '/$tenantId/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIdDashboardSplatRoute = TenantIdDashboardSplatRouteImport.update({
  id: '/$tenantId/dashboard/$',
  path: '/$tenantId/dashboard/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalAppointmentsIndexRoute =
  PatientPortalAppointmentsIndexRouteImport.update({
    id: '/patient-portal/appointments/',
    path: '/patient-portal/appointments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientPortalBillingIndexRoute =
  PatientPortalBillingIndexRouteImport.update({
    id: '/patient-portal/billing/',
    path: '/patient-portal/billing/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientPortalDashboardIndexRoute =
  PatientPortalDashboardIndexRouteImport.update({
    id: '/patient-portal/dashboard/',
    path: '/patient-portal/dashboard/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientPortalDocumentsIndexRoute =
  PatientPortalDocumentsIndexRouteImport.update({
    id: '/patient-portal/documents/',
    path: '/patient-portal/documents/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientPortalFormsIndexRoute = PatientPortalFormsIndexRouteImport.update({
  id: '/patient-portal/forms/',
  path: '/patient-portal/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalLoginIndexRoute = PatientPortalLoginIndexRouteImport.update({
  id: '/patient-portal/login/',
  path: '/patient-portal/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalMessagesIndexRoute =
  PatientPortalMessagesIndexRouteImport.update({
    id: '/patient-portal/messages/',
    path: '/patient-portal/messages/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientPortalNotificationsIndexRoute =
  PatientPortalNotificationsIndexRouteImport.update({
    id: '/patient-portal/notifications/',
    path: '/patient-portal/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientPortalPaymentsIndexRoute =
  PatientPortalPaymentsIndexRouteImport.update({
    id: '/patient-portal/payments/',
    path: '/patient-portal/payments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientPortalTreatmentPlansIndexRoute =
  PatientPortalTreatmentPlansIndexRouteImport.update({
    id: '/patient-portal/treatment-plans/',
    path: '/patient-portal/treatment-plans/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsAppointmentsIndexRoute =
  ReportsAppointmentsIndexRouteImport.update({
    id: '/reports/appointments/',
    path: '/reports/appointments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsCollectionsIndexRoute = ReportsCollectionsIndexRouteImport.update({
  id: '/reports/collections/',
  path: '/reports/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsDashboardIndexRoute = ReportsDashboardIndexRouteImport.update({
  id: '/reports/dashboard/',
  path: '/reports/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPatientsIndexRoute = ReportsPatientsIndexRouteImport.update({
  id: '/reports/patients/',
  path: '/reports/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPractitionersIndexRoute =
  ReportsPractitionersIndexRouteImport.update({
    id: '/reports/practitioners/',
    path: '/reports/practitioners/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsProductionIndexRoute = ReportsProductionIndexRouteImport.update({
  id: '/reports/production/',
  path: '/reports/production/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRecallsIndexRoute = ReportsRecallsIndexRouteImport.update({
  id: '/reports/recalls/',
  path: '/reports/recalls/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRevenueIndexRoute = ReportsRevenueIndexRouteImport.update({
  id: '/reports/revenue/',
  path: '/reports/revenue/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLocationsIndexRoute = SettingsLocationsIndexRouteImport.update({
  id: '/settings/locations/',
  path: '/settings/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrganisationIndexRoute =
  SettingsOrganisationIndexRouteImport.update({
    id: '/settings/organisation/',
    path: '/settings/organisation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsPracticeIndexRoute = SettingsPracticeIndexRouteImport.update({
  id: '/settings/practice/',
  path: '/settings/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityIndexRoute = SettingsSecurityIndexRouteImport.update({
  id: '/settings/security/',
  path: '/settings/security/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/patients/$id': typeof PatientsIdRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/api-keys/': typeof ApiKeysIndexRoute
  '/appointment-reminders/': typeof AppointmentRemindersIndexRoute
  '/appointment-types/': typeof AppointmentTypesIndexRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/chairs/': typeof ChairsIndexRoute
  '/claim-integrations/': typeof ClaimIntegrationsIndexRoute
  '/clinical-notes/': typeof ClinicalNotesIndexRoute
  '/communication-preferences/': typeof CommunicationPreferencesIndexRoute
  '/communication-templates/': typeof CommunicationTemplatesIndexRoute
  '/dashboard-example/': typeof DashboardExampleIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dental-charts/': typeof DentalChartsIndexRoute
  '/fees/': typeof FeesIndexRoute
  '/forbidden/': typeof ForbiddenIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/imaging-images/': typeof ImagingImagesIndexRoute
  '/imaging-integrations/': typeof ImagingIntegrationsIndexRoute
  '/imaging-studies/': typeof ImagingStudiesIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/mfa-verify/': typeof MfaVerifyIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/patient-portal/': typeof PatientPortalIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/periodontal-records/': typeof PeriodontalRecordsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/recalls/': typeof RecallsIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/refunds/': typeof RefundsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/statements/': typeof StatementsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/tooth-conditions/': typeof ToothConditionsIndexRoute
  '/treatment-history/': typeof TreatmentHistoryIndexRoute
  '/treatment-plans/': typeof TreatmentPlansIndexRoute
  '/unauthorized/': typeof UnauthorizedIndexRoute
  '/users/': typeof UsersIndexRoute
  '/$tenantId/dashboard/$': typeof TenantIdDashboardSplatRoute
  '/$tenantId/dashboard/': typeof TenantIdDashboardIndexRoute
  '/patient-portal/appointments/': typeof PatientPortalAppointmentsIndexRoute
  '/patient-portal/billing/': typeof PatientPortalBillingIndexRoute
  '/patient-portal/dashboard/': typeof PatientPortalDashboardIndexRoute
  '/patient-portal/documents/': typeof PatientPortalDocumentsIndexRoute
  '/patient-portal/forms/': typeof PatientPortalFormsIndexRoute
  '/patient-portal/login/': typeof PatientPortalLoginIndexRoute
  '/patient-portal/messages/': typeof PatientPortalMessagesIndexRoute
  '/patient-portal/notifications/': typeof PatientPortalNotificationsIndexRoute
  '/patient-portal/payments/': typeof PatientPortalPaymentsIndexRoute
  '/patient-portal/treatment-plans/': typeof PatientPortalTreatmentPlansIndexRoute
  '/reports/appointments/': typeof ReportsAppointmentsIndexRoute
  '/reports/collections/': typeof ReportsCollectionsIndexRoute
  '/reports/dashboard/': typeof ReportsDashboardIndexRoute
  '/reports/patients/': typeof ReportsPatientsIndexRoute
  '/reports/practitioners/': typeof ReportsPractitionersIndexRoute
  '/reports/production/': typeof ReportsProductionIndexRoute
  '/reports/recalls/': typeof ReportsRecallsIndexRoute
  '/reports/revenue/': typeof ReportsRevenueIndexRoute
  '/settings/locations/': typeof SettingsLocationsIndexRoute
  '/settings/organisation/': typeof SettingsOrganisationIndexRoute
  '/settings/practice/': typeof SettingsPracticeIndexRoute
  '/settings/security/': typeof SettingsSecurityIndexRoute
}
export interface FileRoutesByTo {
  '/patients/$id': typeof PatientsIdRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/api-keys': typeof ApiKeysIndexRoute
  '/appointment-reminders': typeof AppointmentRemindersIndexRoute
  '/appointment-types': typeof AppointmentTypesIndexRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/audit': typeof AuditIndexRoute
  '/chairs': typeof ChairsIndexRoute
  '/claim-integrations': typeof ClaimIntegrationsIndexRoute
  '/clinical-notes': typeof ClinicalNotesIndexRoute
  '/communication-preferences': typeof CommunicationPreferencesIndexRoute
  '/communication-templates': typeof CommunicationTemplatesIndexRoute
  '/dashboard-example': typeof DashboardExampleIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dental-charts': typeof DentalChartsIndexRoute
  '/fees': typeof FeesIndexRoute
  '/forbidden': typeof ForbiddenIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/imaging-images': typeof ImagingImagesIndexRoute
  '/imaging-integrations': typeof ImagingIntegrationsIndexRoute
  '/imaging-studies': typeof ImagingStudiesIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/login': typeof LoginIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/mfa-verify': typeof MfaVerifyIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/patient-portal': typeof PatientPortalIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/periodontal-records': typeof PeriodontalRecordsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/recalls': typeof RecallsIndexRoute
  '/receipts': typeof ReceiptsIndexRoute
  '/refunds': typeof RefundsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/roles': typeof RolesIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/services': typeof ServicesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/statements': typeof StatementsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/tooth-conditions': typeof ToothConditionsIndexRoute
  '/treatment-history': typeof TreatmentHistoryIndexRoute
  '/treatment-plans': typeof TreatmentPlansIndexRoute
  '/unauthorized': typeof UnauthorizedIndexRoute
  '/users': typeof UsersIndexRoute
  '/$tenantId/dashboard/$': typeof TenantIdDashboardSplatRoute
  '/$tenantId/dashboard': typeof TenantIdDashboardIndexRoute
  '/patient-portal/appointments': typeof PatientPortalAppointmentsIndexRoute
  '/patient-portal/billing': typeof PatientPortalBillingIndexRoute
  '/patient-portal/dashboard': typeof PatientPortalDashboardIndexRoute
  '/patient-portal/documents': typeof PatientPortalDocumentsIndexRoute
  '/patient-portal/forms': typeof PatientPortalFormsIndexRoute
  '/patient-portal/login': typeof PatientPortalLoginIndexRoute
  '/patient-portal/messages': typeof PatientPortalMessagesIndexRoute
  '/patient-portal/notifications': typeof PatientPortalNotificationsIndexRoute
  '/patient-portal/payments': typeof PatientPortalPaymentsIndexRoute
  '/patient-portal/treatment-plans': typeof PatientPortalTreatmentPlansIndexRoute
  '/reports/appointments': typeof ReportsAppointmentsIndexRoute
  '/reports/collections': typeof ReportsCollectionsIndexRoute
  '/reports/dashboard': typeof ReportsDashboardIndexRoute
  '/reports/patients': typeof ReportsPatientsIndexRoute
  '/reports/practitioners': typeof ReportsPractitionersIndexRoute
  '/reports/production': typeof ReportsProductionIndexRoute
  '/reports/recalls': typeof ReportsRecallsIndexRoute
  '/reports/revenue': typeof ReportsRevenueIndexRoute
  '/settings/locations': typeof SettingsLocationsIndexRoute
  '/settings/organisation': typeof SettingsOrganisationIndexRoute
  '/settings/practice': typeof SettingsPracticeIndexRoute
  '/settings/security': typeof SettingsSecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/patients/$id': typeof PatientsIdRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/api-keys/': typeof ApiKeysIndexRoute
  '/appointment-reminders/': typeof AppointmentRemindersIndexRoute
  '/appointment-types/': typeof AppointmentTypesIndexRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/chairs/': typeof ChairsIndexRoute
  '/claim-integrations/': typeof ClaimIntegrationsIndexRoute
  '/clinical-notes/': typeof ClinicalNotesIndexRoute
  '/communication-preferences/': typeof CommunicationPreferencesIndexRoute
  '/communication-templates/': typeof CommunicationTemplatesIndexRoute
  '/dashboard-example/': typeof DashboardExampleIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dental-charts/': typeof DentalChartsIndexRoute
  '/fees/': typeof FeesIndexRoute
  '/forbidden/': typeof ForbiddenIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/imaging-images/': typeof ImagingImagesIndexRoute
  '/imaging-integrations/': typeof ImagingIntegrationsIndexRoute
  '/imaging-studies/': typeof ImagingStudiesIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/mfa-verify/': typeof MfaVerifyIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/patient-portal/': typeof PatientPortalIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/periodontal-records/': typeof PeriodontalRecordsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/recalls/': typeof RecallsIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/refunds/': typeof RefundsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/statements/': typeof StatementsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/tooth-conditions/': typeof ToothConditionsIndexRoute
  '/treatment-history/': typeof TreatmentHistoryIndexRoute
  '/treatment-plans/': typeof TreatmentPlansIndexRoute
  '/unauthorized/': typeof UnauthorizedIndexRoute
  '/users/': typeof UsersIndexRoute
  '/$tenantId/dashboard/$': typeof TenantIdDashboardSplatRoute
  '/$tenantId/dashboard/': typeof TenantIdDashboardIndexRoute
  '/patient-portal/appointments/': typeof PatientPortalAppointmentsIndexRoute
  '/patient-portal/billing/': typeof PatientPortalBillingIndexRoute
  '/patient-portal/dashboard/': typeof PatientPortalDashboardIndexRoute
  '/patient-portal/documents/': typeof PatientPortalDocumentsIndexRoute
  '/patient-portal/forms/': typeof PatientPortalFormsIndexRoute
  '/patient-portal/login/': typeof PatientPortalLoginIndexRoute
  '/patient-portal/messages/': typeof PatientPortalMessagesIndexRoute
  '/patient-portal/notifications/': typeof PatientPortalNotificationsIndexRoute
  '/patient-portal/payments/': typeof PatientPortalPaymentsIndexRoute
  '/patient-portal/treatment-plans/': typeof PatientPortalTreatmentPlansIndexRoute
  '/reports/appointments/': typeof ReportsAppointmentsIndexRoute
  '/reports/collections/': typeof ReportsCollectionsIndexRoute
  '/reports/dashboard/': typeof ReportsDashboardIndexRoute
  '/reports/patients/': typeof ReportsPatientsIndexRoute
  '/reports/practitioners/': typeof ReportsPractitionersIndexRoute
  '/reports/production/': typeof ReportsProductionIndexRoute
  '/reports/recalls/': typeof ReportsRecallsIndexRoute
  '/reports/revenue/': typeof ReportsRevenueIndexRoute
  '/settings/locations/': typeof SettingsLocationsIndexRoute
  '/settings/organisation/': typeof SettingsOrganisationIndexRoute
  '/settings/practice/': typeof SettingsPracticeIndexRoute
  '/settings/security/': typeof SettingsSecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/patients/$id'
    | '/settings/$section'
    | '/api-keys/'
    | '/appointment-reminders/'
    | '/appointment-types/'
    | '/appointments/'
    | '/audit/'
    | '/chairs/'
    | '/claim-integrations/'
    | '/clinical-notes/'
    | '/communication-preferences/'
    | '/communication-templates/'
    | '/dashboard-example/'
    | '/dashboard/'
    | '/dental-charts/'
    | '/fees/'
    | '/forbidden/'
    | '/forgot-password/'
    | '/imaging-images/'
    | '/imaging-integrations/'
    | '/imaging-studies/'
    | '/invoices/'
    | '/locations/'
    | '/login/'
    | '/messages/'
    | '/mfa-verify/'
    | '/notifications/'
    | '/patient-portal/'
    | '/patients/'
    | '/payments/'
    | '/periodontal-records/'
    | '/providers/'
    | '/recalls/'
    | '/receipts/'
    | '/refunds/'
    | '/register/'
    | '/reports/'
    | '/reset-password/'
    | '/roles/'
    | '/schedule/'
    | '/services/'
    | '/settings/'
    | '/statements/'
    | '/templates/'
    | '/tooth-conditions/'
    | '/treatment-history/'
    | '/treatment-plans/'
    | '/unauthorized/'
    | '/users/'
    | '/$tenantId/dashboard/$'
    | '/$tenantId/dashboard/'
    | '/patient-portal/appointments/'
    | '/patient-portal/billing/'
    | '/patient-portal/dashboard/'
    | '/patient-portal/documents/'
    | '/patient-portal/forms/'
    | '/patient-portal/login/'
    | '/patient-portal/messages/'
    | '/patient-portal/notifications/'
    | '/patient-portal/payments/'
    | '/patient-portal/treatment-plans/'
    | '/reports/appointments/'
    | '/reports/collections/'
    | '/reports/dashboard/'
    | '/reports/patients/'
    | '/reports/practitioners/'
    | '/reports/production/'
    | '/reports/recalls/'
    | '/reports/revenue/'
    | '/settings/locations/'
    | '/settings/organisation/'
    | '/settings/practice/'
    | '/settings/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/patients/$id'
    | '/settings/$section'
    | '/api-keys'
    | '/appointment-reminders'
    | '/appointment-types'
    | '/appointments'
    | '/audit'
    | '/chairs'
    | '/claim-integrations'
    | '/clinical-notes'
    | '/communication-preferences'
    | '/communication-templates'
    | '/dashboard-example'
    | '/dashboard'
    | '/dental-charts'
    | '/fees'
    | '/forbidden'
    | '/forgot-password'
    | '/imaging-images'
    | '/imaging-integrations'
    | '/imaging-studies'
    | '/invoices'
    | '/locations'
    | '/login'
    | '/messages'
    | '/mfa-verify'
    | '/notifications'
    | '/patient-portal'
    | '/patients'
    | '/payments'
    | '/periodontal-records'
    | '/providers'
    | '/recalls'
    | '/receipts'
    | '/refunds'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/roles'
    | '/schedule'
    | '/services'
    | '/settings'
    | '/statements'
    | '/templates'
    | '/tooth-conditions'
    | '/treatment-history'
    | '/treatment-plans'
    | '/unauthorized'
    | '/users'
    | '/$tenantId/dashboard/$'
    | '/$tenantId/dashboard'
    | '/patient-portal/appointments'
    | '/patient-portal/billing'
    | '/patient-portal/dashboard'
    | '/patient-portal/documents'
    | '/patient-portal/forms'
    | '/patient-portal/login'
    | '/patient-portal/messages'
    | '/patient-portal/notifications'
    | '/patient-portal/payments'
    | '/patient-portal/treatment-plans'
    | '/reports/appointments'
    | '/reports/collections'
    | '/reports/dashboard'
    | '/reports/patients'
    | '/reports/practitioners'
    | '/reports/production'
    | '/reports/recalls'
    | '/reports/revenue'
    | '/settings/locations'
    | '/settings/organisation'
    | '/settings/practice'
    | '/settings/security'
  id:
    | '__root__'
    | '/patients/$id'
    | '/settings/$section'
    | '/api-keys/'
    | '/appointment-reminders/'
    | '/appointment-types/'
    | '/appointments/'
    | '/audit/'
    | '/chairs/'
    | '/claim-integrations/'
    | '/clinical-notes/'
    | '/communication-preferences/'
    | '/communication-templates/'
    | '/dashboard-example/'
    | '/dashboard/'
    | '/dental-charts/'
    | '/fees/'
    | '/forbidden/'
    | '/forgot-password/'
    | '/imaging-images/'
    | '/imaging-integrations/'
    | '/imaging-studies/'
    | '/invoices/'
    | '/locations/'
    | '/login/'
    | '/messages/'
    | '/mfa-verify/'
    | '/notifications/'
    | '/patient-portal/'
    | '/patients/'
    | '/payments/'
    | '/periodontal-records/'
    | '/providers/'
    | '/recalls/'
    | '/receipts/'
    | '/refunds/'
    | '/register/'
    | '/reports/'
    | '/reset-password/'
    | '/roles/'
    | '/schedule/'
    | '/services/'
    | '/settings/'
    | '/statements/'
    | '/templates/'
    | '/tooth-conditions/'
    | '/treatment-history/'
    | '/treatment-plans/'
    | '/unauthorized/'
    | '/users/'
    | '/$tenantId/dashboard/$'
    | '/$tenantId/dashboard/'
    | '/patient-portal/appointments/'
    | '/patient-portal/billing/'
    | '/patient-portal/dashboard/'
    | '/patient-portal/documents/'
    | '/patient-portal/forms/'
    | '/patient-portal/login/'
    | '/patient-portal/messages/'
    | '/patient-portal/notifications/'
    | '/patient-portal/payments/'
    | '/patient-portal/treatment-plans/'
    | '/reports/appointments/'
    | '/reports/collections/'
    | '/reports/dashboard/'
    | '/reports/patients/'
    | '/reports/practitioners/'
    | '/reports/production/'
    | '/reports/recalls/'
    | '/reports/revenue/'
    | '/settings/locations/'
    | '/settings/organisation/'
    | '/settings/practice/'
    | '/settings/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PatientsIdRoute: typeof PatientsIdRoute
  SettingsSectionRoute: typeof SettingsSectionRoute
  ApiKeysIndexRoute: typeof ApiKeysIndexRoute
  AppointmentRemindersIndexRoute: typeof AppointmentRemindersIndexRoute
  AppointmentTypesIndexRoute: typeof AppointmentTypesIndexRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  AuditIndexRoute: typeof AuditIndexRoute
  ChairsIndexRoute: typeof ChairsIndexRoute
  ClaimIntegrationsIndexRoute: typeof ClaimIntegrationsIndexRoute
  ClinicalNotesIndexRoute: typeof ClinicalNotesIndexRoute
  CommunicationPreferencesIndexRoute: typeof CommunicationPreferencesIndexRoute
  CommunicationTemplatesIndexRoute: typeof CommunicationTemplatesIndexRoute
  DashboardExampleIndexRoute: typeof DashboardExampleIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DentalChartsIndexRoute: typeof DentalChartsIndexRoute
  FeesIndexRoute: typeof FeesIndexRoute
  ForbiddenIndexRoute: typeof ForbiddenIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  ImagingImagesIndexRoute: typeof ImagingImagesIndexRoute
  ImagingIntegrationsIndexRoute: typeof ImagingIntegrationsIndexRoute
  ImagingStudiesIndexRoute: typeof ImagingStudiesIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  MfaVerifyIndexRoute: typeof MfaVerifyIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  PatientPortalIndexRoute: typeof PatientPortalIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  PeriodontalRecordsIndexRoute: typeof PeriodontalRecordsIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  RecallsIndexRoute: typeof RecallsIndexRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
  RefundsIndexRoute: typeof RefundsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StatementsIndexRoute: typeof StatementsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ToothConditionsIndexRoute: typeof ToothConditionsIndexRoute
  TreatmentHistoryIndexRoute: typeof TreatmentHistoryIndexRoute
  TreatmentPlansIndexRoute: typeof TreatmentPlansIndexRoute
  UnauthorizedIndexRoute: typeof UnauthorizedIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  TenantIdDashboardSplatRoute: typeof TenantIdDashboardSplatRoute
  TenantIdDashboardIndexRoute: typeof TenantIdDashboardIndexRoute
  PatientPortalAppointmentsIndexRoute: typeof PatientPortalAppointmentsIndexRoute
  PatientPortalBillingIndexRoute: typeof PatientPortalBillingIndexRoute
  PatientPortalDashboardIndexRoute: typeof PatientPortalDashboardIndexRoute
  PatientPortalDocumentsIndexRoute: typeof PatientPortalDocumentsIndexRoute
  PatientPortalFormsIndexRoute: typeof PatientPortalFormsIndexRoute
  PatientPortalLoginIndexRoute: typeof PatientPortalLoginIndexRoute
  PatientPortalMessagesIndexRoute: typeof PatientPortalMessagesIndexRoute
  PatientPortalNotificationsIndexRoute: typeof PatientPortalNotificationsIndexRoute
  PatientPortalPaymentsIndexRoute: typeof PatientPortalPaymentsIndexRoute
  PatientPortalTreatmentPlansIndexRoute: typeof PatientPortalTreatmentPlansIndexRoute
  ReportsAppointmentsIndexRoute: typeof ReportsAppointmentsIndexRoute
  ReportsCollectionsIndexRoute: typeof ReportsCollectionsIndexRoute
  ReportsDashboardIndexRoute: typeof ReportsDashboardIndexRoute
  ReportsPatientsIndexRoute: typeof ReportsPatientsIndexRoute
  ReportsPractitionersIndexRoute: typeof ReportsPractitionersIndexRoute
  ReportsProductionIndexRoute: typeof ReportsProductionIndexRoute
  ReportsRecallsIndexRoute: typeof ReportsRecallsIndexRoute
  ReportsRevenueIndexRoute: typeof ReportsRevenueIndexRoute
  SettingsLocationsIndexRoute: typeof SettingsLocationsIndexRoute
  SettingsOrganisationIndexRoute: typeof SettingsOrganisationIndexRoute
  SettingsPracticeIndexRoute: typeof SettingsPracticeIndexRoute
  SettingsSecurityIndexRoute: typeof SettingsSecurityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api-keys/': {
      id: '/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof ApiKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment-reminders/': {
      id: '/appointment-reminders/'
      path: '/appointment-reminders'
      fullPath: '/appointment-reminders/'
      preLoaderRoute: typeof AppointmentRemindersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment-types/': {
      id: '/appointment-types/'
      path: '/appointment-types'
      fullPath: '/appointment-types/'
      preLoaderRoute: typeof AppointmentTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chairs/': {
      id: '/chairs/'
      path: '/chairs'
      fullPath: '/chairs/'
      preLoaderRoute: typeof ChairsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-integrations/': {
      id: '/claim-integrations/'
      path: '/claim-integrations'
      fullPath: '/claim-integrations/'
      preLoaderRoute: typeof ClaimIntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical-notes/': {
      id: '/clinical-notes/'
      path: '/clinical-notes'
      fullPath: '/clinical-notes/'
      preLoaderRoute: typeof ClinicalNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-preferences/': {
      id: '/communication-preferences/'
      path: '/communication-preferences'
      fullPath: '/communication-preferences/'
      preLoaderRoute: typeof CommunicationPreferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-templates/': {
      id: '/communication-templates/'
      path: '/communication-templates'
      fullPath: '/communication-templates/'
      preLoaderRoute: typeof CommunicationTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-example/': {
      id: '/dashboard-example/'
      path: '/dashboard-example'
      fullPath: '/dashboard-example/'
      preLoaderRoute: typeof DashboardExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-charts/': {
      id: '/dental-charts/'
      path: '/dental-charts'
      fullPath: '/dental-charts/'
      preLoaderRoute: typeof DentalChartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees/': {
      id: '/fees/'
      path: '/fees'
      fullPath: '/fees/'
      preLoaderRoute: typeof FeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden/': {
      id: '/forbidden/'
      path: '/forbidden'
      fullPath: '/forbidden/'
      preLoaderRoute: typeof ForbiddenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imaging-images/': {
      id: '/imaging-images/'
      path: '/imaging-images'
      fullPath: '/imaging-images/'
      preLoaderRoute: typeof ImagingImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imaging-integrations/': {
      id: '/imaging-integrations/'
      path: '/imaging-integrations'
      fullPath: '/imaging-integrations/'
      preLoaderRoute: typeof ImagingIntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imaging-studies/': {
      id: '/imaging-studies/'
      path: '/imaging-studies'
      fullPath: '/imaging-studies/'
      preLoaderRoute: typeof ImagingStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa-verify/': {
      id: '/mfa-verify/'
      path: '/mfa-verify'
      fullPath: '/mfa-verify/'
      preLoaderRoute: typeof MfaVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/': {
      id: '/patient-portal/'
      path: '/patient-portal'
      fullPath: '/patient-portal/'
      preLoaderRoute: typeof PatientPortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodontal-records/': {
      id: '/periodontal-records/'
      path: '/periodontal-records'
      fullPath: '/periodontal-records/'
      preLoaderRoute: typeof PeriodontalRecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recalls/': {
      id: '/recalls/'
      path: '/recalls'
      fullPath: '/recalls/'
      preLoaderRoute: typeof RecallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds/': {
      id: '/refunds/'
      path: '/refunds'
      fullPath: '/refunds/'
      preLoaderRoute: typeof RefundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statements/': {
      id: '/statements/'
      path: '/statements'
      fullPath: '/statements/'
      preLoaderRoute: typeof StatementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tooth-conditions/': {
      id: '/tooth-conditions/'
      path: '/tooth-conditions'
      fullPath: '/tooth-conditions/'
      preLoaderRoute: typeof ToothConditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment-history/': {
      id: '/treatment-history/'
      path: '/treatment-history'
      fullPath: '/treatment-history/'
      preLoaderRoute: typeof TreatmentHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment-plans/': {
      id: '/treatment-plans/'
      path: '/treatment-plans'
      fullPath: '/treatment-plans/'
      preLoaderRoute: typeof TreatmentPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized/': {
      id: '/unauthorized/'
      path: '/unauthorized'
      fullPath: '/unauthorized/'
      preLoaderRoute: typeof UnauthorizedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantId/dashboard/': {
      id: '/$tenantId/dashboard/'
      path: '/$tenantId/dashboard'
      fullPath: '/$tenantId/dashboard/'
      preLoaderRoute: typeof TenantIdDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantId/dashboard/$': {
      id: '/$tenantId/dashboard/$'
      path: '/$tenantId/dashboard/$'
      fullPath: '/$tenantId/dashboard/$'
      preLoaderRoute: typeof TenantIdDashboardSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/appointments/': {
      id: '/patient-portal/appointments/'
      path: '/patient-portal/appointments'
      fullPath: '/patient-portal/appointments/'
      preLoaderRoute: typeof PatientPortalAppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/billing/': {
      id: '/patient-portal/billing/'
      path: '/patient-portal/billing'
      fullPath: '/patient-portal/billing/'
      preLoaderRoute: typeof PatientPortalBillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/dashboard/': {
      id: '/patient-portal/dashboard/'
      path: '/patient-portal/dashboard'
      fullPath: '/patient-portal/dashboard/'
      preLoaderRoute: typeof PatientPortalDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/documents/': {
      id: '/patient-portal/documents/'
      path: '/patient-portal/documents'
      fullPath: '/patient-portal/documents/'
      preLoaderRoute: typeof PatientPortalDocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/forms/': {
      id: '/patient-portal/forms/'
      path: '/patient-portal/forms'
      fullPath: '/patient-portal/forms/'
      preLoaderRoute: typeof PatientPortalFormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/login/': {
      id: '/patient-portal/login/'
      path: '/patient-portal/login'
      fullPath: '/patient-portal/login/'
      preLoaderRoute: typeof PatientPortalLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/messages/': {
      id: '/patient-portal/messages/'
      path: '/patient-portal/messages'
      fullPath: '/patient-portal/messages/'
      preLoaderRoute: typeof PatientPortalMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/notifications/': {
      id: '/patient-portal/notifications/'
      path: '/patient-portal/notifications'
      fullPath: '/patient-portal/notifications/'
      preLoaderRoute: typeof PatientPortalNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/payments/': {
      id: '/patient-portal/payments/'
      path: '/patient-portal/payments'
      fullPath: '/patient-portal/payments/'
      preLoaderRoute: typeof PatientPortalPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/treatment-plans/': {
      id: '/patient-portal/treatment-plans/'
      path: '/patient-portal/treatment-plans'
      fullPath: '/patient-portal/treatment-plans/'
      preLoaderRoute: typeof PatientPortalTreatmentPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/appointments/': {
      id: '/reports/appointments/'
      path: '/reports/appointments'
      fullPath: '/reports/appointments/'
      preLoaderRoute: typeof ReportsAppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/collections/': {
      id: '/reports/collections/'
      path: '/reports/collections'
      fullPath: '/reports/collections/'
      preLoaderRoute: typeof ReportsCollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/dashboard/': {
      id: '/reports/dashboard/'
      path: '/reports/dashboard'
      fullPath: '/reports/dashboard/'
      preLoaderRoute: typeof ReportsDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/patients/': {
      id: '/reports/patients/'
      path: '/reports/patients'
      fullPath: '/reports/patients/'
      preLoaderRoute: typeof ReportsPatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/practitioners/': {
      id: '/reports/practitioners/'
      path: '/reports/practitioners'
      fullPath: '/reports/practitioners/'
      preLoaderRoute: typeof ReportsPractitionersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/production/': {
      id: '/reports/production/'
      path: '/reports/production'
      fullPath: '/reports/production/'
      preLoaderRoute: typeof ReportsProductionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/recalls/': {
      id: '/reports/recalls/'
      path: '/reports/recalls'
      fullPath: '/reports/recalls/'
      preLoaderRoute: typeof ReportsRecallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/revenue/': {
      id: '/reports/revenue/'
      path: '/reports/revenue'
      fullPath: '/reports/revenue/'
      preLoaderRoute: typeof ReportsRevenueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/locations/': {
      id: '/settings/locations/'
      path: '/settings/locations'
      fullPath: '/settings/locations/'
      preLoaderRoute: typeof SettingsLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organisation/': {
      id: '/settings/organisation/'
      path: '/settings/organisation'
      fullPath: '/settings/organisation/'
      preLoaderRoute: typeof SettingsOrganisationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/practice/': {
      id: '/settings/practice/'
      path: '/settings/practice'
      fullPath: '/settings/practice/'
      preLoaderRoute: typeof SettingsPracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security/': {
      id: '/settings/security/'
      path: '/settings/security'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof SettingsSecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PatientsIdRoute: PatientsIdRoute,
  SettingsSectionRoute: SettingsSectionRoute,
  ApiKeysIndexRoute: ApiKeysIndexRoute,
  AppointmentRemindersIndexRoute: AppointmentRemindersIndexRoute,
  AppointmentTypesIndexRoute: AppointmentTypesIndexRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  AuditIndexRoute: AuditIndexRoute,
  ChairsIndexRoute: ChairsIndexRoute,
  ClaimIntegrationsIndexRoute: ClaimIntegrationsIndexRoute,
  ClinicalNotesIndexRoute: ClinicalNotesIndexRoute,
  CommunicationPreferencesIndexRoute: CommunicationPreferencesIndexRoute,
  CommunicationTemplatesIndexRoute: CommunicationTemplatesIndexRoute,
  DashboardExampleIndexRoute: DashboardExampleIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DentalChartsIndexRoute: DentalChartsIndexRoute,
  FeesIndexRoute: FeesIndexRoute,
  ForbiddenIndexRoute: ForbiddenIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  ImagingImagesIndexRoute: ImagingImagesIndexRoute,
  ImagingIntegrationsIndexRoute: ImagingIntegrationsIndexRoute,
  ImagingStudiesIndexRoute: ImagingStudiesIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  MfaVerifyIndexRoute: MfaVerifyIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  PatientPortalIndexRoute: PatientPortalIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  PeriodontalRecordsIndexRoute: PeriodontalRecordsIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  RecallsIndexRoute: RecallsIndexRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
  RefundsIndexRoute: RefundsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StatementsIndexRoute: StatementsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ToothConditionsIndexRoute: ToothConditionsIndexRoute,
  TreatmentHistoryIndexRoute: TreatmentHistoryIndexRoute,
  TreatmentPlansIndexRoute: TreatmentPlansIndexRoute,
  UnauthorizedIndexRoute: UnauthorizedIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  TenantIdDashboardSplatRoute: TenantIdDashboardSplatRoute,
  TenantIdDashboardIndexRoute: TenantIdDashboardIndexRoute,
  PatientPortalAppointmentsIndexRoute: PatientPortalAppointmentsIndexRoute,
  PatientPortalBillingIndexRoute: PatientPortalBillingIndexRoute,
  PatientPortalDashboardIndexRoute: PatientPortalDashboardIndexRoute,
  PatientPortalDocumentsIndexRoute: PatientPortalDocumentsIndexRoute,
  PatientPortalFormsIndexRoute: PatientPortalFormsIndexRoute,
  PatientPortalLoginIndexRoute: PatientPortalLoginIndexRoute,
  PatientPortalMessagesIndexRoute: PatientPortalMessagesIndexRoute,
  PatientPortalNotificationsIndexRoute: PatientPortalNotificationsIndexRoute,
  PatientPortalPaymentsIndexRoute: PatientPortalPaymentsIndexRoute,
  PatientPortalTreatmentPlansIndexRoute: PatientPortalTreatmentPlansIndexRoute,
  ReportsAppointmentsIndexRoute: ReportsAppointmentsIndexRoute,
  ReportsCollectionsIndexRoute: ReportsCollectionsIndexRoute,
  ReportsDashboardIndexRoute: ReportsDashboardIndexRoute,
  ReportsPatientsIndexRoute: ReportsPatientsIndexRoute,
  ReportsPractitionersIndexRoute: ReportsPractitionersIndexRoute,
  ReportsProductionIndexRoute: ReportsProductionIndexRoute,
  ReportsRecallsIndexRoute: ReportsRecallsIndexRoute,
  ReportsRevenueIndexRoute: ReportsRevenueIndexRoute,
  SettingsLocationsIndexRoute: SettingsLocationsIndexRoute,
  SettingsOrganisationIndexRoute: SettingsOrganisationIndexRoute,
  SettingsPracticeIndexRoute: SettingsPracticeIndexRoute,
  SettingsSecurityIndexRoute: SettingsSecurityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
